In [ ]:
# 
# 18 June 2020
# 
# Plotting tutorial
# Reference: https://matplotlib.org/tutorials/introductory/pyplot.html
# https://matplotlib.org/3.1.0/api/_as_gen/matplotlib.pyplot.figure.html
# https://www.tutorialspoint.com/matplotlib/index.htm
#

In [78]:
import numpy as np
import matplotlib.pyplot as plt
import scipy.linalg as la

In [80]:
#TASK2.0


fig = plt.figure(figsize = (10,6))
x = np.linspace(-2,3,100)

# Amplitude of the sine wave is sine of a variable like time

y1 = x**2 - (2*x) - 3
y2 = np.sin(10*x)+ np.cos(3*x)
y3 =  np.sin(2*3.14*x) + np.exp(2*x) + (x-2.5)

plt.plot(x, y1, c = 'r', label = 'f(x)1')
plt.plot(x, y2, c = 'b', label = 'f(x)2')
plt.plot(x, y3, c = 'g' , label = 'f(x)3' )

plt.grid(True, which='both')

plt.legend()
plt.show()

TypeError: ignored

In [81]:




#TASK2.1
M = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])
N = np.array([[0, 0, 0], [0, 0, 0], [0, 0, 0]])

m = 0 
n = 0 

def is_square(M) :
 
  for m in range(len(M)):
    m+=1
    for n in range(len(M[0])):
      n = n+1
    
  if(m==n):
    print('square',m,n)
    return m,n


def is_symmetrical(M,N) :
  if len(M)==len(N[0]) and len(N)==len(M[0]):
    print(M,'and',N,'are symmetic')



def is_diagonal(M):
  zero_metrix = 0
  for i in range(len(M)):
     for j in  range(len(M)):
          if((i != j ) and (M[i][j]!=0)):
            print('This metrix is not diagnal')
            return False
          if((M[i][j]==0)):
            zero_metrix += 1
            if zero_metrix == len(M):
                  print(zero_metrix)
                  print('This metrix also be zero metrix')
  return True

    
  

is_square(M)
is_symmetrical(M,N)
#is_zerometrix include in is diagonal function
is_diagonal(M)
#transpose metrix
TN = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(list(map(list, zip(*TN))))








TypeError: ignored

In [61]:
#TASK2.2

a = np.array([[ 5, 1 ,3], 
                  [ 1, 1 ,1], 
                  [ 1, 2 ,1]])
b = np.array([1, 2, 3])
print(a.dot(b))

[16  6  8]


In [65]:
#TASK2.3
def determinantOfMatrix(mat,n): 
  
    temp = [0]*n # temporary array for storing row   
    total=1 
    det=1  # initialize result 
  
    # loop for traversing the diagonal elements  
    for i in range(0,n): 
        index=i  # initialize the index 
  
        # finding the index which has non zero value   
        while(mat[index][i] == 0 and index < n): 
            index+=1
     
        if(index == n): # if there is non zero element 
            # the determinat of matrix as zero 
            continue
  
        if(index != i): 
            # loop for swaping the diagonal element row and index row 
            for j in range(0,n): 
                mat[index][j],mat[i][j] = mat[i][j],mat[index][j] 
                  
            # determinant sign changes when we shift rows   
            # go through determinant properties   
            det = det*int(pow(-1,index-i)) 
    
        # storing the values of diagonal row elements  
        for j in range(0,n): 
            temp[j] = mat[i][j] 
           
        #traversing every row below the diagonal element 
        for j in range(i+1,n): 
            num1 = temp[i]     # value of diagonal element 
            num2 = mat[j][i]   # value of next row element 
  
            # traversing every column of row   
            # and multiplying to every row   
            for k in range(0,n): 
                # multiplying to make the diagonal   
                # element and next row element equal 
  
                mat[j][k] = (num1*mat[j][k]) - (num2*temp[k]) 
  
            total = total * num1 # Det(kA)=kDet(A); 
  
    #mulitplying the diagonal elements to get determinant 
    for i in range(0,n): 
         det = det*mat[i][i] 
  
  
    return int(det/total) #Det(kA)/k=Det(A);   
  
#Drivers code 
if __name__ == "__main__": 
   
    mat=[[4, 5, 2, -1],[3, 6, 7, 3],[-2, 1, 4, -3],[1, 5, 5, 7]] 
    N=len(mat) 
    print("Determinant of the matrix is : ",determinantOfMatrix(mat,N)) 





Determinant of the matrix is :  -424


In [66]:
#TASK2.4

np.array=([1, 1, -1, -2],[0, 2, 1, 3],[0, 1, 1, 3],[0, 2, 1, 4]) 
print (np.array)

#minor
def __init__(self, *rows):
        """
        Accepts either a matrix, a 2-dimensional list of numbers,
        a list with a matrix width ( int ), or a series of one-dimensional lists of numbers.
        :Parameters:
            rows : list
                Arguments for creating a matrix.
        """
        self._width = 0
        self._height = 0
        self._value = list()

        if rows:
            # if the value passed into the constructor is a matrix
            if len(rows) == 1 and type(rows[0]) == type(self):
                for row in rows[0].value:
                    newRow = list()
                    for item in row:  # this should make a deep copy.
                        newRow.append(item)
                    self.addRow(*newRow)
            # if the value passed into the constructor is a two-dimensional list
            elif len(rows) == 1 and type(rows[0]) in MATRIX_VALID_COLLECTIONS and                       type(rows[0][0]) in MATRIX_VALID_COLLECTIONS:
                for row in rows[0]:
                    newRow = list()
                    for item in row:  # this should make a deep copy.
                        newRow.append(item)
                    self.addRow(*newRow)
            # if the value passed into the constructor is a list followed by a matrix width
            elif ((len(rows) == 2) and (type(rows[0]) in MATRIX_VALID_COLLECTIONS) and (
                type(rows[1]) in MATRIX_VALID_INTS)):
                if (len(rows[0]) % rows[1]):
                    raise ValueError(
                        'Invalid list length for matrix construction, must be a multiple of width argument')
                newRow = list()
                for i in range(len(rows[0])):
                    if (i and (not i % rows[1])):  # i > 0 and a multiple of the given width.
                        self.addRow(*newRow)
                        newRow = list()
                    newRow.append(rows[0][i])
                # when we get here, there should still be one row left in the "buffer", so
                self.addRow(*newRow)
            # if the value passed into the constructor is several lists
            else:
                for row in rows:
                    if not (type(row) in MATRIX_VALID_COLLECTIONS):
                        raise TypeError("Constructor arguments must be of type 'list' or 'tuple'")  # fix this!
                    self.addRow(*row)

def minor(self, i, j):
        """
        The Minor of a matrix
        :rtype: number
        :returns: The minor of the item at column i, row j
        """
        if not self.isSquare():
            raise ValueError("Minor is not defined for non-square matrix")
        if (self._height == 1 and self._width == 1):
            raise ValueError("Minor is not defined for 1x1 matrix")
        m = Matrix(self)
        m.deleteRow(i)
        m.deleteColumn(j)
        return m.determinant()


print("Minor of the matrix:")
print(m)

#cofactor
co = np.linalg.inv(np.array).T * np.linalg.det(np.array)
print("Cofactor of the matrix:")
print(co)

#adjoint
adj = np.linalg.det(np.array) *  np.linalg.inv(np.array)
print("Adjoint of the matrix:")
print(adj)

#inverse
inv =  np.linalg.inv(np.array)
print("Inverse of the matrix:")
print(inv)

([1, 1, -1, -2], [0, 2, 1, 3], [0, 1, 1, 3], [0, 2, 1, 4])
Minor of the matrix:
0
Cofactor of the matrix:
[[ 1.  0.  0.  0.]
 [-1.  1.  2. -1.]
 [ 3. -1.  2.  0.]
 [-1.  0. -3.  1.]]
Adjoint of the matrix:
[[ 1. -1.  3. -1.]
 [ 0.  1. -1.  0.]
 [ 0.  2.  2. -3.]
 [ 0. -1.  0.  1.]]
Inverse of the matrix:
[[ 1. -1.  3. -1.]
 [ 0.  1. -1.  0.]
 [ 0.  2.  2. -3.]
 [ 0. -1.  0.  1.]]


In [77]:
#TASK2.5
A = np.array([[1,0],[0,-2]]) 
w, v = np.linalg.eig(A)

print('eigenvalues')
print(w)
print('eigenvector')
print(v)

lam = w[1]
print('find lamda')
print(lam)

print('if lamda = 7')
x = w[1]/7
print(x)



TypeError: ignored